services:
  app-staging:
    image: gabcat/merchtrack:latest
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    # networks:
    #   - staging
    deploy:
      mode: "replicated"
      replicas: 2
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      APP_ENV: production
      NEXT_PUBLIC_NODE_ENV: production
      NEXT_RUNTIME: nodejs
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}

      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
      NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: /dashboard
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: /dashboard
      NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: /onboarding

      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN}
      SENTRY_TRACES_SAMPLE_RATE: 0.4
      SENTRY_SUPPRESS_TURBOPACK_WARNING: 1
      SENTRY_DSN: ${SENTRY_DSN}

      NEXT_PUBLIC_DATADOG_APPLICATION_ID: ${NEXT_PUBLIC_DATADOG_APPLICATION_ID}
      NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: ${NEXT_PUBLIC_DATADOG_CLIENT_TOKEN}
      NEXT_PUBLIC_DATADOG_SITE: ${NEXT_PUBLIC_DATADOG_SITE}
      NEXT_PUBLIC_DATADOG_SERVICE_NAME: ${NEXT_PUBLIC_DATADOG_SERVICE_NAME}

      NEXT_PUBLIC_CF_BEACON_TOKEN: ${NEXT_PUBLIC_CF_BEACON_TOKEN}
      CLOUDFLARE_R2_ACCESS_KEY_ID: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
      CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
      CLOUDFLARE_R2_BUCKET_NAME: ${CLOUDFLARE_R2_BUCKET_NAME}
      CLOUDFLARE_R2_ENDPOINT: ${CLOUDFLARE_R2_ENDPOINT}
      CLOUDFLARE_R2_PUBLIC_URL: ${CLOUDFLARE_R2_PUBLIC_URL}
      CLOUDFLARE_R2_PUBLIC_DOMAIN: ${CLOUDFLARE_R2_PUBLIC_DOMAIN}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

# networks:
#   staging:
#     external: true