name: Export Secrets to Doppler

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to export secrets to"
        required: true
        default: "Production"
        type: choice
        options:
          - Production
          - Staging

jobs:
  export-to-doppler:
    environment: ${{ github.event.inputs.environment }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    name: export GitHub secrets to Doppler
    steps:
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      # - name: Upload Secrets to Doppler
      #   run: |
      #     doppler secrets upload --project "$DOPPLER_TARGET_PROJECT" --config "$DOPPLER_TARGET_CONFIG" --silent <(echo "$GITHUB_SECRETS" | jq 'del(.github_token, .DOPPLER_TOKEN, .DOPPLER_PRODUCTION_PROJECT, .DOPPLER_PRODUCTION_CONFIG, .DOPPLER_STAGING_PROJECT, .DOPPLER_STAGING_CONFIG) | with_entries( .key |= ascii_upcase )')
      #   shell: bash
      #   env:
      #     DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      #     DOPPLER_TARGET_PROJECT: ${{ secrets.DOPPLER_TARGET_PROJECT }}
      #     DOPPLER_TARGET_CONFIG: ${{ secrets.DOPPLER_TARGET_CONFIG }}
      #     GITHUB_SECRETS: ${{ toJson(secrets) }}
