name: 5. MIGRATION - Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    environment: Migration
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}

          
      - name: Create Database Snapshot
        run: |
          SNAPSHOT_NAME="merchtrack-db-sgp1-snapshot-$(date +%Y%m%d%H%M%S)"
          aws lightsail create-relational-database-snapshot \
            --relational-database-name merchtrack-db-sgp1 \
            --relational-database-snapshot-name "$SNAPSHOT_NAME"
          echo "Created snapshot: $SNAPSHOT_NAME"


      - name: Check Database Public Accessibility
        id: check-db
        run: |
          DB_INFO=$(aws lightsail get-relational-database --relational-database-name merchtrack-db-sgp1)
          IS_PUBLIC=$(echo "$DB_INFO" | jq -r '.relationalDatabase.publiclyAccessible')
          echo "is_public=$IS_PUBLIC" >> $GITHUB_OUTPUT


      - name: Open Database to Public Network
        if: ${{ steps.check-db.outputs.is_public == 'false' }}
        run: |
          aws lightsail update-relational-database \
            --relational-database-name merchtrack-db-sgp1 \
            --publicly-accessible


      - name: Run Database Migration
        run: |
          pnpm prisma migrate deploy

      - name: Close Database to Public Network
        run: |
          aws lightsail update-relational-database \
            --relational-database-name merchtrack-db-sgp1 \
            --no-publicly-accessible

