name: 4. PRODUCTION - Deploy and version tag image

on:
  workflow_dispatch:
    inputs:
      commit_tag:
        description: 'Commit tag'
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: 'ubuntu-latest'
    environment: Production
    env:
      DEPLOYED_LINK: https://merchtrack.tech
      ENVIRONMENT: Production
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Check if actor is repository owner
      run: |
        if [ "${{ github.actor }}" != "${{ github.repository_owner }}" ]; then
          echo "This workflow can only be run by the repository owner."
          exit 1
        fi

    - name: Validate commit tag format
      run: |
        if [[ ! "${{ github.event.inputs.commit_tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid commit tag format. Expected format: <number>.<number>.<number>"
          exit 1
        fi

    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - uses: actions/setup-node@v4
      with:
        node-version: '20.11'
  
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install --shamefully-hoist

    - name: Prisma Migration Deploy
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
      run: pnpm migrate

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    
    - name: Pull staging image
      run: |
        docker pull gabcat/merchtrack:staging
    
    - name: Tag image for production
      run: |
        docker tag gabcat/merchtrack:staging gabcat/merchtrack:${{ github.event.inputs.commit_tag }}
        docker tag gabcat/merchtrack:staging gabcat/merchtrack:latest
    
    - name: Push production tags to Docker Hub
      run: |
        docker push gabcat/merchtrack:${{ github.event.inputs.commit_tag }}
        docker push gabcat/merchtrack:latest
