name: 3. STAGING - Build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: 'ubuntu-latest'
    environment: Staging
    env:
      DEPLOYED_LINK: https://staging.merchtrack.tech
      ENVIRONMENT: Staging
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Check if actor is repository owner
      run: |
        if [ "${{ github.actor }}" != "${{ github.repository_owner }}" ]; then
          echo "This workflow can only be run by the repository owner."
          exit 1
        fi

    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Create env file
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
      run: |
        echo "DATABASE_URL=${DATABASE_URL}" > .env

    - name: Check IP
      run: curl ifconfig.me

    - name: Log in to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build client image and push to Docker Hub
      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
      with:
        context: .
        file: ./Dockerfile
        tags: |
          gabcat/merchtrack:staging
        cache-from: |
          type=registry,ref=gabcat/merchtrack:cache
          type=registry,ref=gabcat/merchtrack:staging
        cache-to: type=inline
        push: true
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
